/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Line286Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Line_286.png';
import Line287Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Line_287.png';
import Line2861Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Line_286_1.png';
import Line2871Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Line_287_1.png';
import Line2862Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Line_286_2.png';
import Line2872Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Line_287_2.png';
import Line2863Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Line_286_3.png';
import Line2873Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Line_287_3.png';
import Line2864Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Line_286_4.png';
import Line2874Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Line_287_4.png';
import Line2865Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Line_286_5.png';
import Line2875Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Line_287_5.png';
import Line2866Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Line_286_6.png';
import Line2876Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Line_287_6.png';
import Line2867Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Line_286_7.png';
import Line2877Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Line_287_7.png';
import Caminho3513Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Caminho_3513.png';
import Elipse214Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Elipse_214.png';
import Elipse215Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Elipse_215.png';
import Caminho3514Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Caminho_3514.png';
import Caminho3522Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Caminho_3522.png';
import Caminho3523Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Caminho_3523.png';
import Caminho3524Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Caminho_3524.png';
import IconColorImage from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Icon_Color.png';
import Line2868Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Line_286_8.png';
import Ellipse3Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Ellipse_3.png';
import União14Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Uni_o_14.png';
import União11Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Uni_o_11.png';
import União9Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Uni_o_9.png';
import Caminho93Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Caminho_93.png';
import Caminho94Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Caminho_94.png';
import União6Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Uni_o_6.png';
import Caminho117Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Caminho_117.png';
import União13Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Uni_o_13.png';
import Retângulo52Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Ret_ngulo_52.png';
import Retângulo54Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Ret_ngulo_54.png';
import União3Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Uni_o_3.png';
import Caminho9944Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Caminho_9944.png';
import Caminho9945Image from 'src/assets/images/GerenciamentoDetalhesdoprojetoAdicionarvaga_Caminho_9945.png';
import { styled } from '@mui/material/styles';

const GerenciamentoDetalhe = styled('div')({
  backgroundColor: `rgba(245, 246, 247, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1023px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Rectangle199 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  width: `1061px`,
  height: `967px`,
  position: `absolute`,
  left: `332px`,
  top: `56px`,
});

const Group34 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1018px`,
  height: `583px`,
  left: `354px`,
  top: `360px`,
});

const Group17 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1018px`,
  height: `68px`,
  left: `0px`,
  top: `39px`,
});

const Line286 = styled('img')({
  height: `0px`,
  width: `1018px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Line287 = styled('img')({
  height: `0px`,
  width: `1018px`,
  position: `absolute`,
  left: `0px`,
  top: `68px`,
});

const Group16 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `549px`,
  height: `23px`,
  left: `59px`,
  top: `23px`,
});

const Group26 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `549px`,
  height: `23px`,
  left: `0px`,
  top: `0px`,
});

const PessoaDesenvolvedora = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `358px`,
  height: `23px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const PapelTécnico = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `148px`,
  height: `23px`,
  position: `absolute`,
  left: `401px`,
  top: `0px`,
}));

const Group18 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1018px`,
  height: `68px`,
  left: `0px`,
  top: `107px`,
});

const Line2861 = styled('img')({
  height: `0px`,
  width: `1018px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Line2871 = styled('img')({
  height: `0px`,
  width: `1018px`,
  position: `absolute`,
  left: `0px`,
  top: `68px`,
});

const Group161 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `549px`,
  height: `23px`,
  left: `59px`,
  top: `23px`,
});

const Group261 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `549px`,
  height: `23px`,
  left: `0px`,
  top: `0px`,
});

const PessoaDesenvolvedora1 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `358px`,
  height: `23px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const PapelTécnico1 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `148px`,
  height: `23px`,
  position: `absolute`,
  left: `401px`,
  top: `0px`,
}));

const Group19 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1018px`,
  height: `68px`,
  left: `0px`,
  top: `175px`,
});

const Line2862 = styled('img')({
  height: `0px`,
  width: `1018px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Line2872 = styled('img')({
  height: `0px`,
  width: `1018px`,
  position: `absolute`,
  left: `0px`,
  top: `68px`,
});

const Group162 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `549px`,
  height: `23px`,
  left: `59px`,
  top: `23px`,
});

const Group262 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `549px`,
  height: `23px`,
  left: `0px`,
  top: `0px`,
});

const PessoaDesenvolvedora2 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `358px`,
  height: `23px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const PapelTécnico2 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `148px`,
  height: `23px`,
  position: `absolute`,
  left: `401px`,
  top: `0px`,
}));

const Group20 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1018px`,
  height: `68px`,
  left: `0px`,
  top: `243px`,
});

const Line2863 = styled('img')({
  height: `0px`,
  width: `1018px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Line2873 = styled('img')({
  height: `0px`,
  width: `1018px`,
  position: `absolute`,
  left: `0px`,
  top: `68px`,
});

const Group163 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `549px`,
  height: `23px`,
  left: `59px`,
  top: `23px`,
});

const Group263 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `549px`,
  height: `23px`,
  left: `0px`,
  top: `0px`,
});

const PessoaUxDesigner = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `358px`,
  height: `23px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const PapelTécnico3 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `148px`,
  height: `23px`,
  position: `absolute`,
  left: `401px`,
  top: `0px`,
}));

const Group21 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1018px`,
  height: `68px`,
  left: `0px`,
  top: `311px`,
});

const Line2864 = styled('img')({
  height: `0px`,
  width: `1018px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Line2874 = styled('img')({
  height: `0px`,
  width: `1018px`,
  position: `absolute`,
  left: `0px`,
  top: `68px`,
});

const Group164 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `549px`,
  height: `23px`,
  left: `59px`,
  top: `23px`,
});

const Group264 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `549px`,
  height: `23px`,
  left: `0px`,
  top: `0px`,
});

const PessoaDesenvolvedora3 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `358px`,
  height: `23px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Shadow = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `148px`,
  height: `23px`,
  position: `absolute`,
  left: `401px`,
  top: `0px`,
}));

const Group22 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1018px`,
  height: `68px`,
  left: `0px`,
  top: `379px`,
});

const Line2865 = styled('img')({
  height: `0px`,
  width: `1018px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Line2875 = styled('img')({
  height: `0px`,
  width: `1018px`,
  position: `absolute`,
  left: `0px`,
  top: `68px`,
});

const Group165 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `549px`,
  height: `23px`,
  left: `59px`,
  top: `23px`,
});

const Group265 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `549px`,
  height: `23px`,
  left: `0px`,
  top: `0px`,
});

const PessoaProductOwner = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `358px`,
  height: `23px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const PapelTécnico4 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `148px`,
  height: `23px`,
  position: `absolute`,
  left: `401px`,
  top: `0px`,
}));

const Group23 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1018px`,
  height: `68px`,
  left: `0px`,
  top: `447px`,
});

const Line2866 = styled('img')({
  height: `0px`,
  width: `1018px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Line2876 = styled('img')({
  height: `0px`,
  width: `1018px`,
  position: `absolute`,
  left: `0px`,
  top: `68px`,
});

const Group166 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `549px`,
  height: `23px`,
  left: `59px`,
  top: `23px`,
});

const Group266 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `549px`,
  height: `23px`,
  left: `0px`,
  top: `0px`,
});

const PessoaRedatora = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `358px`,
  height: `23px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Shadow1 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `148px`,
  height: `23px`,
  position: `absolute`,
  left: `401px`,
  top: `0px`,
}));

const Group24 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1018px`,
  height: `68px`,
  left: `0px`,
  top: `515px`,
});

const Line2867 = styled('img')({
  height: `0px`,
  width: `1018px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Line2877 = styled('img')({
  height: `0px`,
  width: `1018px`,
  position: `absolute`,
  left: `0px`,
  top: `68px`,
});

const Group167 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `549px`,
  height: `23px`,
  left: `59px`,
  top: `23px`,
});

const Group267 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `549px`,
  height: `23px`,
  left: `0px`,
  top: `0px`,
});

const PessoaVisualizaçãoDe = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `358px`,
  height: `23px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Shadow2 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `148px`,
  height: `23px`,
  position: `absolute`,
  left: `401px`,
  top: `0px`,
}));

const Vaga = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(126, 126, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0.24px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  position: `absolute`,
  left: `61px`,
  top: `1px`,
}));

const TipoDaVaga = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(126, 126, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0.24px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  position: `absolute`,
  left: `460px`,
  top: `0px`,
}));

const Área = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(126, 126, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0.24px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  position: `absolute`,
  left: `678px`,
  top: `1px`,
}));

const Lightining = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(31, 31, 31, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `300`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `40px`,
  textTransform: `none`,
  width: `887px`,
  height: `46px`,
  position: `absolute`,
  left: `402px`,
  top: `124px`,
}));

const Dds2ButtonFlex = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `885px`,
  top: `170px`,
});

const DdsButtonBase = styled('div')({
  border: `1px solid rgba(0, 99, 184, 1)`,
  boxSizing: `border-box`,
  borderRadius: `2px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `12px 20px`,
  margin: `0px`,
});

const IconLeft = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24px`,
  height: `24px`,
  margin: `0px`,
});

const Frame = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `21px`,
  height: `20px`,
  left: `1px`,
  top: `2px`,
  overflow: `hidden`,
});

const Caminho3513 = styled('img')({
  height: `9.5px`,
  width: `6.83px`,
  position: `absolute`,
  left: `14px`,
  top: `7px`,
});

const Elipse214 = styled('img')({
  height: `4.5px`,
  width: `4.39px`,
  position: `absolute`,
  left: `16px`,
  top: `2px`,
});

const Elipse215 = styled('img')({
  height: `6.5px`,
  width: `6.35px`,
  position: `absolute`,
  left: `8px`,
  top: `0px`,
});

const Caminho3514 = styled('img')({
  height: `12.56px`,
  width: `10.76px`,
  position: `absolute`,
  left: `6px`,
  top: `7px`,
});

const Caminho3522 = styled('img')({
  height: `1.91px`,
  width: `2.2px`,
  position: `absolute`,
  left: `9px`,
  top: `5px`,
});

const Caminho3523 = styled('img')({
  height: `11px`,
  width: `10.74px`,
  position: `absolute`,
  left: `0px`,
  top: `5px`,
});

const Caminho3524 = styled('img')({
  height: `5.96px`,
  width: `4.71px`,
  position: `absolute`,
  left: `3px`,
  top: `7px`,
});

const Label = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 99, 184, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  margin: `0px 0px 0px 16px`,
}));

const IconRight = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24px`,
  height: `24px`,
  margin: `0px 0px 0px 16px`,
});

const IconColor = styled('img')({
  height: `0px`,
  width: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `2px`,
});

const Group2 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `797.5px`,
  height: `0px`,
  left: `595px`,
  top: `288px`,
});

const Line2868 = styled('img')({
  height: `0px`,
  width: `797.5px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame1 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  width: `5.23px`,
  height: `24.92px`,
  left: `1323px`,
  top: `124px`,
  overflow: `hidden`,
});

const Ellipse3 = styled('img')({
  height: `22px`,
  width: `22px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `1203px`,
  top: `18px`,
});

const DellHeroes = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(99, 99, 99, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `28px`,
  textTransform: `none`,
  position: `absolute`,
  left: `332px`,
  top: `16px`,
}));

const Seg2DeNovDe2022 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(99, 99, 99, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  position: `absolute`,
  left: `444px`,
  top: `20px`,
}));

const Frame2 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `257px`,
  height: `25px`,
  left: `15px`,
  top: `16px`,
  overflow: `hidden`,
});

const Logos = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `255.63px`,
  height: `19.15px`,
  left: `0px`,
  top: `2px`,
});

const Grupo198 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `83.1px`,
  height: `14.74px`,
  left: `173px`,
  top: `1px`,
});

const União14 = styled('img')({
  height: `13.46px`,
  width: `9.01px`,
  position: `absolute`,
  left: `59px`,
  top: `1px`,
});

const União11 = styled('img')({
  height: `13.46px`,
  width: `16.04px`,
  position: `absolute`,
  left: `67px`,
  top: `1px`,
});

const União9 = styled('img')({
  height: `13.46px`,
  width: `14.69px`,
  position: `absolute`,
  left: `44px`,
  top: `1px`,
});

const Grupo137 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `15.18px`,
  height: `14.74px`,
  left: `2px`,
  top: `0px`,
});

const Caminho93 = styled('img')({
  height: `2.2px`,
  width: `2.77px`,
  position: `absolute`,
  left: `1px`,
  top: `13px`,
});

const Caminho94 = styled('img')({
  height: `14.74px`,
  width: `15.18px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const União6 = styled('img')({
  height: `13.66px`,
  width: `12.9px`,
  position: `absolute`,
  left: `33px`,
  top: `1px`,
});

const Caminho117 = styled('img')({
  height: `14.73px`,
  width: `15.17px`,
  position: `absolute`,
  left: `1px`,
  top: `0px`,
});

const União13 = styled('img')({
  height: `14.73px`,
  width: `16.66px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Retângulo52 = styled('img')({
  height: `1.08px`,
  width: `0.85px`,
  position: `absolute`,
  left: `47px`,
  top: `5px`,
});

const Retângulo54 = styled('img')({
  height: `1.08px`,
  width: `0.77px`,
  position: `absolute`,
  left: `48px`,
  top: `5px`,
});

const Grupo145 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `13.47px`,
  height: `14.08px`,
  left: `19px`,
  top: `1px`,
});

const União3 = styled('img')({
  height: `14.08px`,
  width: `13.47px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const DelltechLogoPrmBlue = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `147.03px`,
  height: `19.15px`,
  left: `0px`,
  top: `0px`,
});

const Caminho9944 = styled('img')({
  height: `18.2px`,
  width: `100.36px`,
  position: `absolute`,
  left: `47px`,
  top: `1px`,
});

const Caminho9945 = styled('img')({
  height: `15.9px`,
  width: `46.67px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Desenvolvimento = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `148px`,
  height: `23px`,
  position: `absolute`,
  left: `1032px`,
  top: `420px`,
}));

const Desenvolvimento1 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `148px`,
  height: `23px`,
  position: `absolute`,
  left: `1032px`,
  top: `489px`,
}));

const Desenvolvimento2 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `148px`,
  height: `23px`,
  position: `absolute`,
  left: `1032px`,
  top: `557px`,
}));

const Design = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `148px`,
  height: `23px`,
  position: `absolute`,
  left: `1032px`,
  top: `625px`,
}));

const Desenvolvimento3 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `148px`,
  height: `23px`,
  position: `absolute`,
  left: `1032px`,
  top: `693px`,
}));

const InovaçãoEGestão = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `148px`,
  height: `23px`,
  position: `absolute`,
  left: `1032px`,
  top: `761px`,
}));

const Design1 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `148px`,
  height: `23px`,
  position: `absolute`,
  left: `1032px`,
  top: `829px`,
}));

const Desenvolvimento4 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 14, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.08px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `148px`,
  height: `23px`,
  position: `absolute`,
  left: `1032px`,
  top: `897px`,
}));

const Group43 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `800px`,
  height: `546px`,
  left: `320px`,
  top: `272px`,
});

const Dds2Modal = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `800px`,
  height: `546px`,
  left: `0px`,
  top: `0px`,
});

const SizeLargeHeadingTrue = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `800px`,
  height: `547px`,
  left: `0px`,
  top: `0px`,
});

const BaseModal = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  width: `800px`,
  height: `489px`,
  left: `0px`,
  top: `0px`,
});

function GerenciamentoDetalhesDoProjeto(props) {
  return (
    <GerenciamentoDetalhe className={props.className}>
      <Rectangle199></Rectangle199>
      <Group34>
        <Group17>
          <Line286 src={Line286Image} loading="lazy" alt={'Line 286'} />
          <Line287 src={Line287Image} loading="lazy" alt={'Line 287'} />
          <Group16>
            <Group26>
              <PessoaDesenvolvedora>
                {`Pessoa desenvolvedora Backend`}
              </PessoaDesenvolvedora>
              <PapelTécnico>{`Papel técnico`}</PapelTécnico>
            </Group26>
          </Group16>
        </Group17>
        <Group18>
          <Line2861 src={Line2861Image} loading="lazy" alt={'Line 286'} />
          <Line2871 src={Line2871Image} loading="lazy" alt={'Line 287'} />
          <Group161>
            <Group261>
              <PessoaDesenvolvedora1>
                {`Pessoa desenvolvedora Java`}
              </PessoaDesenvolvedora1>
              <PapelTécnico1>{`Papel técnico`}</PapelTécnico1>
            </Group261>
          </Group161>
        </Group18>
        <Group19>
          <Line2862 src={Line2862Image} loading="lazy" alt={'Line 286'} />
          <Line2872 src={Line2872Image} loading="lazy" alt={'Line 287'} />
          <Group162>
            <Group262>
              <PessoaDesenvolvedora2>
                {`Pessoa desenvolvedora .Net`}
              </PessoaDesenvolvedora2>
              <PapelTécnico2>{`Papel técnico`}</PapelTécnico2>
            </Group262>
          </Group162>
        </Group19>
        <Group20>
          <Line2863 src={Line2863Image} loading="lazy" alt={'Line 286'} />
          <Line2873 src={Line2873Image} loading="lazy" alt={'Line 287'} />
          <Group163>
            <Group263>
              <PessoaUxDesigner>{`Pessoa UX Designer`}</PessoaUxDesigner>
              <PapelTécnico3>{`Papel técnico`}</PapelTécnico3>
            </Group263>
          </Group163>
        </Group20>
        <Group21>
          <Line2864 src={Line2864Image} loading="lazy" alt={'Line 286'} />
          <Line2874 src={Line2874Image} loading="lazy" alt={'Line 287'} />
          <Group164>
            <Group264>
              <PessoaDesenvolvedora3>
                {`Pessoa desenvolvedora Salesforce`}
              </PessoaDesenvolvedora3>
              <Shadow>{`Shadow`}</Shadow>
            </Group264>
          </Group164>
        </Group21>
        <Group22>
          <Line2865 src={Line2865Image} loading="lazy" alt={'Line 286'} />
          <Line2875 src={Line2875Image} loading="lazy" alt={'Line 287'} />
          <Group165>
            <Group265>
              <PessoaProductOwner>{`Pessoa Product Owner`}</PessoaProductOwner>
              <PapelTécnico4>{`Papel técnico`}</PapelTécnico4>
            </Group265>
          </Group165>
        </Group22>
        <Group23>
          <Line2866 src={Line2866Image} loading="lazy" alt={'Line 286'} />
          <Line2876 src={Line2876Image} loading="lazy" alt={'Line 287'} />
          <Group166>
            <Group266>
              <PessoaRedatora>{`Pessoa Redatora`}</PessoaRedatora>
              <Shadow1>{`Shadow`}</Shadow1>
            </Group266>
          </Group166>
        </Group23>
        <Group24>
          <Line2867 src={Line2867Image} loading="lazy" alt={'Line 286'} />
          <Line2877 src={Line2877Image} loading="lazy" alt={'Line 287'} />
          <Group167>
            <Group267>
              <PessoaVisualizaçãoDe>
                {`Pessoa Visualização de Dados`}
              </PessoaVisualizaçãoDe>
              <Shadow2>{`Shadow`}</Shadow2>
            </Group267>
          </Group167>
        </Group24>
        <Vaga>{`Vaga`}</Vaga>
        <TipoDaVaga>{`Tipo da vaga`}</TipoDaVaga>
        <Área>{`Área`}</Área>
      </Group34>
      <Lightining>{`Lightining`}</Lightining>
      <Dds2ButtonFlex>
        <DdsButtonBase>
          <IconLeft>
            <Frame>
              <Caminho3513
                src={Caminho3513Image}
                loading="lazy"
                alt={'Caminho 3513'}
              />
              <Elipse214
                src={Elipse214Image}
                loading="lazy"
                alt={'Elipse 214'}
              />
              <Elipse215
                src={Elipse215Image}
                loading="lazy"
                alt={'Elipse 215'}
              />
              <Caminho3514
                src={Caminho3514Image}
                loading="lazy"
                alt={'Caminho 3514'}
              />
              <Caminho3522
                src={Caminho3522Image}
                loading="lazy"
                alt={'Caminho 3522'}
              />
              <Caminho3523
                src={Caminho3523Image}
                loading="lazy"
                alt={'Caminho 3523'}
              />
              <Caminho3524
                src={Caminho3524Image}
                loading="lazy"
                alt={'Caminho 3524'}
              />
            </Frame>
          </IconLeft>
          <Label>{`Entre em contato`}</Label>
          {false && (
            <IconRight>
              <IconColor
                src={IconColorImage}
                loading="lazy"
                alt={'Icon Color'}
              />
            </IconRight>
          )}
        </DdsButtonBase>
      </Dds2ButtonFlex>
      <Group2>
        <Line2868 src={Line2868Image} loading="lazy" alt={'Line 286'} />
      </Group2>
      <Frame1></Frame1>
      <Ellipse3 src={Ellipse3Image} loading="lazy" alt={'Ellipse 3'} />
      <DellHeroes>{`Dell Heroes`}</DellHeroes>
      <Seg2DeNovDe2022>{`seg, 2 de nov. de 2022`}</Seg2DeNovDe2022>
      <Frame2>
        <Logos>
          <Grupo198>
            <União14 src={União14Image} loading="lazy" alt={'União 14'} />
            <União11 src={União11Image} loading="lazy" alt={'União 11'} />
            <União9 src={União9Image} loading="lazy" alt={'União 9'} />
            <Grupo137>
              <Caminho93
                src={Caminho93Image}
                loading="lazy"
                alt={'Caminho 93'}
              />
              <Caminho94
                src={Caminho94Image}
                loading="lazy"
                alt={'Caminho 94'}
              />
            </Grupo137>
            <União6 src={União6Image} loading="lazy" alt={'União 6'} />
            <Caminho117
              src={Caminho117Image}
              loading="lazy"
              alt={'Caminho 117'}
            />
            <União13 src={União13Image} loading="lazy" alt={'União 13'} />
            <Retângulo52
              src={Retângulo52Image}
              loading="lazy"
              alt={'Retângulo 52'}
            />
            <Retângulo54
              src={Retângulo54Image}
              loading="lazy"
              alt={'Retângulo 54'}
            />
            <Grupo145>
              <União3 src={União3Image} loading="lazy" alt={'União 3'} />
            </Grupo145>
          </Grupo198>
          <DelltechLogoPrmBlue>
            <Caminho9944
              src={Caminho9944Image}
              loading="lazy"
              alt={'Caminho 9944'}
            />
            <Caminho9945
              src={Caminho9945Image}
              loading="lazy"
              alt={'Caminho 9945'}
            />
          </DelltechLogoPrmBlue>
        </Logos>
      </Frame2>
      <Desenvolvimento>{`Desenvolvimento`}</Desenvolvimento>
      <Desenvolvimento1>{`Desenvolvimento`}</Desenvolvimento1>
      <Desenvolvimento2>{`Desenvolvimento`}</Desenvolvimento2>
      <Design>{`Design`}</Design>
      <Desenvolvimento3>{`Desenvolvimento`}</Desenvolvimento3>
      <InovaçãoEGestão>{`Inovação e gestão`}</InovaçãoEGestão>
      <Design1>{`Design`}</Design1>
      <Desenvolvimento4>{`Desenvolvimento`}</Desenvolvimento4>
      <Group43>
        <Dds2Modal>
          <SizeLargeHeadingTrue>
            <BaseModal></BaseModal>
          </SizeLargeHeadingTrue>
        </Dds2Modal>
      </Group43>
    </GerenciamentoDetalhe>
  );
}

export default GerenciamentoDetalhesDoProjeto;
